- app/controllers/cars_controller.rb
- app/views/cars/index.html.erb
- app/views/cars/show.html.erb
- config/routes.rb
> added a delete action

- Gemfile
- Gemfile.lock
- app/policies/application_policy.rb
> added the pundit gem

- app/controllers/bookings_controller.rb
- app/models/booking.rb
- db/migrate/20220531100540_create_bookings.rb
- db/schema.rb
- test/controllers/bookings_controller_test.rb
- test/models/booking_test.rb
> Add bookings model and controller

- app/controllers/bookings_controller.rb
- app/views/bookings/_form.html.erb
- app/views/bookings/new.html.erb
- app/views/cars/new.html.erb
- app/views/cars/show.html.erb
review code, tell me if smt is wrong
> completed booking views and controller essentials

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_homepage_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_show_card.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/cars/index.html.erb
- app/views/cars/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
> fixed navbar and added some basic styling

- app/controllers/application_controller.rb
- app/controllers/cars_controller.rb
- app/policies/booking_policy.rb
- app/policies/car_policy.rb
- test/policies/booking_policy_test.rb
- test/policies/car_policy_test.rb
> removed pundit

- config/environments/production.rb
> added production cloudinary storage

- app/controllers/bookings_controller.rb
added a @booking.status = "pending" in the bookings#create
> added a line to change the booking status upon creation

- app/controllers/bookings_controller.rb
- app/controllers/cars_controller.rb
- app/controllers/dashboards_controller.rb
- app/views/cars/_edit_form.html.erb
- app/views/cars/_form.html.erb
- app/views/cars/edit.html.erb
- app/views/cars/index.html.erb
- app/views/cars/new.html.erb
- app/views/cars/show.html.erb
- app/views/dashboards/index.html.erb
- config/routes.rb
- db/migrate/20220601190825_add_price_to_cars.rb
- db/schema.rb
added dashboard views, controllers, removed the ability of user to delete a car if there is a booking on it,
> Car delete conditions visuals

- app/controllers/cars_controller.rb
- app/views/cars/_edit_form.html.erb
- app/views/cars/_form.html.erb
- app/views/cars/edit.html.erb
- app/views/cars/index.html.erb
- app/views/cars/new.html.erb
- app/views/cars/show.html.erb
- app/views/dashboards/index.html.erb
- config/routes.rb
- db/migrate/20220601190825_add_price_to_cars.rb
- db/schema.rb
> Update functionality to cars

- app/assets/stylesheets/components/_show_card.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/cars_controller.rb
- app/models/car.rb
- app/views/cars/index.html.erb
- app/views/dashboards/index.html.erb
> Change index owned cars

- app/models/car.rb
- app/views/dashboards/index.html.erb
added some conditional styling to index page
> changed dashboard delete button

- app/assets/stylesheets/components/_show_card.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/cars/_edit_form.html.erb
- app/views/cars/_form.html.erb
- app/views/cars/edit.html.erb
- app/views/dashboards/index.html.erb
> Changed dashboard and form

- app/views/dashboards/index.html.erb
> changed button

- app/assets/stylesheets/pages/_index.scss
- app/controllers/bookings_controller.rb
- app/controllers/cars_controller.rb
- app/controllers/dashboards_controller.rb
- app/views/cars/edit.html.erb
- app/views/dashboards/index.html.erb
> idk what I changed but it works

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_show_card.scss
- app/views/bookings/_form.html.erb
- app/views/bookings/new.html.erb
- app/views/dashboards/index.html.erb
- app/views/shared/_navbar.html.erb
> Changed create page

- app/controllers/cars_controller.rb
- app/controllers/dashboards_controller.rb
- app/views/cars/edit.html.erb
added controller actions for the search bar in cas_controller#index
> quick fix for search

- app/controllers/bookings_controller.rb
Changed the booking controller and CSS styling to better reflect the status
> made reject booking button work on dashboard

- app/assets/stylesheets/pages/_index.scss
- app/controllers/cars_controller.rb
> refined the search

- app/controllers/cars_controller.rb
> Refined search two
